set nocompatible

set hlsearch

set ambiwidth=double

filetype plugin indent on
syntax enable
syntax on

"if has('gui_running')
"    set background=light              " 适应亮色背景
    colorscheme molokai
"else
"    set background=dark               " 适应暗色背景
"    colorscheme peachpuff
"endif

set nobackup
set nowritebackup 
set noswapfile

set backspace=indent,eol,start

set showmatch
set number
set ruler
set wrap
set smartindent
set matchpairs=(:),[:],{:},<:>
set whichwrap=b,s,<,>,[,]
set autoindent
"set foldmethod=indent syntax
set guifont=文泉驿等宽微米黑
set columns=80
set lines=30

set showcmd                           " 回显输入的命令
set showmode                          " 显示当前的模式
set fileformat=unix
"set mouse=a
set laststatus=2 
set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1

