version: '3'
services:
  redis:
    image: redis
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=sentry
  sentry:
    image: sentry
    environment:
      - SENTRY_SECRET_KEY=123
      - SENTRY_REDIS_HOST=redis
      - SENTRY_POSTGRES_HOST=postgres
      - SENTRY_DB_USER=sentry
      - SENTRY_DB_PASSWORD=123
    links:
      - redis
      - postgres
    ports:
      - 8080:9000
